### ISSUE TITLE
Branching strategy in REM

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel-remrem-semantics#148]
### Description
Today the various versions are released with the same major release, so making it difficult to fix the issues identified on a protocol edition.

### Motivation
We have issues with older edition that needs to be addressed and we cannot upgrade to latest edition of protocol yet.

### Benefits
If we have branching strategy we know that the releases will be based on protocol editions and easy to fix and deliver.

### Possible Drawbacks
Without the branching strategy it is difficult to align on the fixes needed to be applied on certain protocol editions

**Comment by z-sztrom** [comment]
Solution could be introduction of _maintenance_ branches. A maintenance branch is created when release cannot be created on master branch, see examples below.

~~~~
master   ... 1.0.0 -- 1.0.1 ... 2.1.4 ... 3.2.5 -- 4.0.0    ...   4.1.13 -- 4.1.14 -- ...
                            \                  \                        /
                             \                  \                      /
1.0-maintenance                1.0.2 -- 1.0.3    \                    /
                                                  \                  /
                                                   \                /
3.2-maintenance                                      3.2.6 -- 3.2.7 -- 3.2.8
~~~~

Here, the following scenario is depicted:
* After some initial development versions `1.0.0` and `1.0.1` are released.
* Development continues and series of versions `2.0.X` is released.
* Later, when the latest release is `2.1.4`, a bug on release `1.0.1` is reported and needs to be fixed. So far all of the releases were released on master branch, but now fix of the bug cannot be released on master after release `1.0.1`. That is why a new branch `1.0-maintenance` is introduced and the bug is fixed in releases `1.0.2`. If they are other fixes or improvements of series `1.0`, they are released on the maintenance branch.
* Suppose a situation when the latest release is `4.1.13` and a fix must be done for `3.2.5`. Analogously to series `1.0`, a maintenance branch `3.2-maintenance` is created and the fix is released by `3.2.6` and `3.2.7`. If an issue, fixed by `3.2.7`, is also detected in `4.0` series, the fix needs to be merged to master and released as `4.1.14`.
* Other fixes or improvements of series `3.2` continue on branch `3.2-maintenance`.

Note, that every release is _tagged_; this is common practice.

**Comment by e-backmark-ericsson** [comment]
@z-sztrom could we close this issue now since https://github.com/eiffel-community/eiffel-remrem/pull/12 was merged?

**Comment by z-sztrom** [comment]
Published in https://github.com/eiffel-community/eiffel-remrem/blob/master/overview.md#branching-strategy.
